# Generated by Django 4.2.2 on 2024-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GR', '0002_addtocarproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocarproducts',
            name='price',
            field=models.FloatField(),
        ),
    ]
