# Generated by Django 5.0.2 on 2024-03-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GR', '0005_alter_feedback_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedBack',
            new_name='userQuary',
        ),
    ]
